package com.ronaldo.gestor.front.frame;

import com.ronaldo.gestor.back.controlador.Controlador;
import com.ronaldo.gestor.front.paneles.PanelMenuPrincipal;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author ronaldo
 */
public class FrameGeneral extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGeneral.class.getName());
    private static final int TAMAÑO_ANCHO = 1000;
    private static final int TAMAÑO_ALTO = 700;

    private Controlador controlador;
    /**
     * Creates new form FrameGeneral
     */
    public FrameGeneral() {
        initComponents();
        controlador = new Controlador();
        ponerPanelEnFramePrincipal(new PanelMenuPrincipal(this.controlador));
        panelGeneral.setLayout(new GridLayout());
    }

    public static void ponerPanelEnFramePrincipal(JPanel panel) {
        panel.setSize(TAMAÑO_ANCHO, TAMAÑO_ALTO);
        panel.setLocation(0, 0);
        panelGeneral.removeAll();
        panelGeneral.add(panel, BorderLayout.CENTER);
        panelGeneral.revalidate();
        panelGeneral.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Supermercado");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        panelGeneral.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
